title: "Code with Shabib"
email: ""
description: "Mobile Architect & Tech Lead | iOS, Swift, React Native"
url: "https://www.codewithshabib.com"
github_username: shabib87
minimal_mistakes_skin: "custom"
search: true
copyright: "Code with Shabib"
copyright_url: "https://www.codewithshabib.com"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Toronto

include:
  - _pages
  - googlef46b5fcb1c61719b.html

google_analytics: G-LMPSDMRRVL

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: "Ahmad Shabibul Hossain"
  avatar : "/assets/images/bio-photo.jpg"
  bio: "Converting ☕️ into code since 2007 👨‍💻"
  location: "Toronto, Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ahmadshabibulhossain/"
      target: "_blank"
      rel: "noopener noreferrer"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/shabib87"
      target: "_blank"
      rel: "noopener noreferrer"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shabib87"
      target: "_blank"
      rel: "noopener noreferrer"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ahmadshabibulhossain"
      target: "_blank"
      rel: "noopener noreferrer"

# Comments
comments:
  provider: "giscus"
  giscus:
    repo: "shabib87/shabib87.github.io"
    repo_id: "R_kgDOOQ_c3g"
    category: "General"
    category_id: "DIC_kwDOOQ_c3s4CpSY0"
    mapping: "pathname"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "top"
    theme: "preferred_color_scheme"
    lang: "en"
    loading: "lazy"

share:
  provider: "social-share"
  target: "_blank"
  social_share:
    - "linkedin"
    - "twitter"
    - "facebook"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true 
      comments: true
      share: true
      related: true
      sidebar:
        nav: "none"  # This disables navigation in sidebar for posts
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false  # Disable comments on pages

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

seo:
  title: "Code with Shabib - Mobile Development Blog"
  description: "Expert insights on iOS, Swift, and React Native development from a Mobile Architect & Tech Lead"
  author: "Ahmad Shabibul Hossain"
  linkedin:
    username: "ahmadshabibulhossain"
    card: summary_large_image

responsive_image:
  sizes:
    - width: 800
      quality: 80
    - width: 400
      quality: 80
  base_path: assets/images
  strip: true
  save_to_site: true
